
#  pbs template
#  to be run with qsub -v FILE=name_of_ini_file, ID=whatever_label
source .bashrc
conda activate covid
cd /storage/home/vidnerova/covid/model-m/tests/
export PYTHONPATH=$PYTHONPATH:/storage/home/vidnerova/covid/model-m/models:/storage/home/vidnerova/covid/model-m/graphs:/storage/home/vidnerova/covid/model-m/utils:/storage/home/vidnerova/covid/model-m/policies

#for J in "0 7" "8 15" "16 23" "24 31" "32 39" "40 47" "48 55" "56 63" "64 71" "72 79" "80 87" "88 95" "96 99"; do



# run processes and store pids in array
for I in `seq $INTERVAL`; do
	python run_experiment.py -r $P ${FILE}  ${TID}_${I} > ${TID}_${I}.log  &
	pids[${I}]=$!
done

echo ${pids[*]} > pids.log

# wait for all pids
for pid in ${pids[*]}; do
 	wait $pid
done
unset pids
#done 